services:
  budget-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///data/budget.db
      - SECRET_KEY=your_secret_key_here_change_in_production